# numpy チートシート

In [1]:
import numpy as np

# np.expand_dims(img_tensor,axis=0)
img_tensorに0列目に次元を増やす。axisで場所を指定

# np.zeros((15,16))
 15×16の要素がすべて0のnumpy配列を作成

# np.where(X>=0,1,-1)
 行列X中の様子で0以上(条件)のものは1,0以下のものは-1にする
 ステップ関数で利用

In [8]:
a = np.arange(9).reshape((3, 3))
print(a)
# 行列aの要素で4以上のものは１,4以下は-1にする
np.where(a>=4,1,-1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[-1, -1, -1],
       [-1,  1,  1],
       [ 1,  1,  1]])

# np.arange(1,10,2)
Python のrange(1,10,2)に対応し、等差数列のnumpy行列を作成

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## np.meshgrid(x,y)
格子座標を作成する便利な関数