# Pandas チートシート

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## データセット準備

## Breast Cancer wisons
2クラス30特徴量

In [2]:
import urllib
try:
    df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases'
                     '/breast-cancer-wisconsin/wdbc.data', header=None)
except urllib.error.URLError:
    df = pd.read_csv('https://raw.githubusercontent.com/rasbt/'
                     'python-machine-learning-book/master/code/'
                     'datasets/wdbc/wdbc.data', header=None)
print('rows, columns:', df.shape)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X=df.iloc[:,2:]
y=df.iloc[:,1]
y=le.fit_transform(y)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
df.head()

rows, columns: (569, 32)


0  1      2      3       4       5        6        7       8   \
0    842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001   
1    842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869   
2  84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974   
3  84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414   
4  84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980   

        9   ...     22     23      24      25      26      27      28      29  \
0  0.14710  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1  0.07017  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2  0.12790  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3  0.10520  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4  0.10430  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

       30       31  
0  0.4601  0.11890  
1  0.2750  0.08902  
2  0.3613  0.08758  
3  0.6638  0.17300  
4  0.2364  0.07678  

[5 rows x 32 columns]

## Boston Housingデータ
回帰モデル、13特徴量

In [24]:
from sklearn.model_selection import train_test_split
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/'
                 'housing/housing.data',
                 header=None,
                 sep='\s+')
df.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 
              'NOX', 'RM', 'AGE', 'DIS', 'RAD', 
              'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
display(df.head())

X=df.iloc[:,:df.shape[1]-1]
y=df['MEDV']


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

## pd.DataFrame({'col1':[1,2,3],'col2':[4,5,6]})
DataFrameを自分で作るときに便利

In [23]:
pd.DataFrame({'col1':[1,2,3],'col2':[4,5,6]})

col1  col2
0     1     4
1     2     5
2     3     6

## df.describe()
お手軽に各列の平均や最大などの基本情報をまとめてくれる。数値データのみ表示するので、文字列データの特徴量には何の操作もしてくれない

In [5]:
df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677082   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

## df.info()
各列の特徴量の数と、欠損情報、型の情報を返してくれる。数値データと文字列データを把握したいときに役に立つ

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null int64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null int64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
MEDV       506 non-null float64
dtypes: float64(12), int64(2)
memory usage: 55.4 KB


## pd.merge(df_left, df_right, how='inner', on='key')
２つのDFを、共通部分で結合

## df.rename(columns={'A': 'a'}, index={'ONE': 'one'}
カラム名を新しい変更

## train[['x_0','y_0','z_0']]
 複数の列を表示するときはカラム名をリストにいれる

## train[['x_0','y_0','z_0']].values
DataFrameの列の値をNumpy配列で返す

In [21]:
print(df['MEDV'].values[:5])
print(type(df['MEDV'].values))

[24.  21.6 34.7 33.4 36.2]
<class 'numpy.ndarray'>


## df.apply(lambda x: (x - x.mean()) / x.std())
各列に対して処理を行う

## df.groupby(['A', 'B']).sum()
A,B列でグルーピングして、各列で合計をとる

## df.loc[[1:3], ['Age', 'Height']]
1:3行,Age,Height列にアクセス locは名前による参照

## df.iloc[[1:3], [0,2]]
1:3行　0,2列にアクセス　ilocは番号による参照



## df.loc[df["columns"]>=5]
DFはbool型のシーケンスを指定してTrueのみを取り出すフィルタリングができる  
df.loc[df['カラム']を含む条件式]  
二つの条件　df.loc[df["banana"]>=5][df['apple']<=3] も可能

## df.iloc[0:100,[0,2]]
 ilocは行番号と列番号で位置を指定できる
 0~100行、1,3列を取得

## df.isnull()
欠損値NaNである要素はTrue,正常に値が入っている場合はFalseとなったDataFrameを返す

## df.isnull().any()
各特徴量ごとに、欠損値が一つでも含まれる場合は、True,欠損値が一つもない場合はFalseを表示。

## df.drop(['col1','col2','col3'],axis=1)
column名の列をすべて削除する。正解ラベルを別の変数に入れてから、列から削除したいときに便利

In [14]:
df_=df
display(df_.head(3))
df_=df_.drop(['CRIM','INDUS','NOX'],axis=1)
display(df_.head(3))

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7

ZN  CHAS     RM   AGE     DIS  RAD    TAX  PTRATIO       B  LSTAT  MEDV
0  18.0     0  6.575  65.2  4.0900    1  296.0     15.3  396.90   4.98  24.0
1   0.0     0  6.421  78.9  4.9671    2  242.0     17.8  396.90   9.14  21.6
2   0.0     0  7.185  61.1  4.9671    2  242.0     17.8  392.83   4.03  34.7

## df.dropna()
欠損値を持つ行を削除。df.dropna(axis=1)で列を削除  
how='all'ですべての列がNaNである行だけ削除。　thresh=4で非NaN値が4つ未満の行を削除　subset=['C']特定の列(C列)にNaNが含まれている行を削除

In [6]:
from io import StringIO
csv_data = '''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''
df=pd.read_csv(StringIO(csv_data))
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [7]:
df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

In [10]:
df.dropna(subset=['C'])

A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

## df['C'].fillna(df['C'].mean())
## df.fillna("FILLNUM")
fillna()中の値で欠損値NaNを穴埋めする。平均値を入れいる場合は上のやり方、中央値は.median(),最貧値は.mode()を使う  
列を指定せずにdf.fillna(df.mean())とすれば、各列の平均値が欠損値に穴埋めされるので便利

In [16]:
df.fillna(df.mean())

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   7.5  8.0
2  10.0  11.0  12.0  6.0

## 参考 sklearnを用いた欠損値補完
### from sklearn.preprcessing import Imputer
### imr=Imputer(missing_value='NaN',strategy='mean',axis=1)
### imputed_data=imr.fit_transform(df.values)
一度、欠損値補完のインスタンスを生成しなければいけない。標準化StandardScalerを用いるときと同じ手順  
numpyの配列ndarrayを生成するので注意

In [21]:
from sklearn.preprocessing import Imputer
imr=Imputer(missing_values='NaN',strategy='mean',axis=1)
imputed_data=imr.fit_transform(df.values)
imputed_data

array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  6.33333333,  8.        ],
       [10.        , 11.        , 12.        , 11.        ]])

## df.['col'].map(label_mapping)
要素を置換する。カテゴリ特徴量を数値データにする際に使える。  
置換されない値はNaNをとる。

In [53]:
df = pd.DataFrame([['green', 'M', 10.1, 'class1'],
                   ['red', 'L', 13.5, 'class2'],
                   ['blue', 'XL', 15.3, 'class1']])
df.columns = ['color', 'size', 'price', 'classlabel']
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

### 順序特徴量のマッピング
特徴量間に順序が明確に決まってる場合は、段階的に数値を当てはめても良い

In [54]:
size_mapping={'XL':3,'L':2,'M':1}
df['size']=df['size'].map(size_mapping)
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

### 正解クラスラベルのエンコーディング
クラスラベルが数値出ないときに、対応させるように自分で変える。

In [55]:
# マッピング用の対応を作成
class_mapping={label:idx for idx,label in enumerate(df['classlabel'])}
print(class_mapping)

df['classlabel']=df['classlabel'].map(class_mapping)
df

{'class1': 2, 'class2': 1}


color  size  price  classlabel
0  green     1   10.1           2
1    red     2   13.5           1
2   blue     3   15.3           2

## 参考　sklearnでのラベルエンコーディング
### from skleran.preprocessing import LabelEncoder
### class_le=LabelEncoder()
### y=class_le.fit_transform(df['classlabel'].values)
順序特徴量は反映されないので注意が必要

In [56]:
from sklearn.preprocessing import LabelEncoder
print(df['size'])
print(df['classlabel'])
class_le=LabelEncoder()
print(class_le.fit_transform(df['size']))
print(class_le.fit_transform(df['classlabel']))

0    1
1    2
2    3
Name: size, dtype: int64
0    2
1    1
2    2
Name: classlabel, dtype: int64
[0 1 2]
[1 0 1]


## pd.get_dummies(df ,columns=[ 'col1', 'col2'] )
one-hotエンコーディングを手軽に行ってくれる便利なライブラリ。特徴量が多くなりすぎる可能性があるので注意   
columnsに何も指定しないと、文字データのみにone-hot-encodingを行うので、数値特徴量もエンコーディングしたい場合は、列名を指定する

In [57]:
print(df)
# 文字データも数値データもエンコードされる
df=pd.get_dummies(df,columns=['color','size'])
print(df)

   color  size  price  classlabel
0  green     1   10.1           2
1    red     2   13.5           1
2   blue     3   15.3           2
   price  classlabel  color_blue  color_green  color_red  size_1  size_2  \
0   10.1           2           0            1          0       1       0   
1   13.5           1           0            0          1       0       1   
2   15.3           2           1            0          0       0       0   

   size_3  
0       0  
1       0  
2       1  


## df.value_counts()
各特徴量に何種類の値があるか数えあげてくれる。クラス数の確認などに便利

In [8]:
df[1].value_counts()

B    357
M    212
Name: 1, dtype: int64

## df.dtype
データ型を表示する。

## df['col'].astype('str')
データ型を変形する。1列にしか使えないので注意

In [40]:
df=pd.DataFrame({'col1':[1,2,3],'col2':['red','green','blue']})
print(df['col1'].dtype)
df['col1']=df['col1'].astype('str')
print(df['col1'].dtype)

int64
object


col1   col2
0     1    red
1     2  green
2     3   blue